version: '3.5'
services:
  zabbix-server:
    hostname: zabbix-server
    container_name: zabbix-server
    image: zabbix/zabbix-server-mysql:ubuntu-6.4-latest
    restart: unless-stopped
    depends_on:
      - mysql
    ports:
      - "10051:10051"
    volumes:
      - "/etc/localtime:/etc/localtime:ro"
      - "/etc/timezone:/etc/timezone:ro"
    links:
      - mysql
    environment:
      - ZBX_HOSTNAME=
      - MYSQL_USER=zabbix
      - DB_SERVER_HOST=mysql-server
      - MYSQL_DATABASE=zabbix
      - MYSQL_PASSWORD=Zabbix2024
      - ZBX_ALLOWUNSUPPORTEDDBVERSIONS=1
      - ZBX_NODEADDRESS=localhost:10051
    tmpfs: /tmp
    ulimits:
      nproc: 65535
      nofile:
        soft: 20000
        hard: 40000
    deploy:
      replicas: 1
    cpus: 0.5
    mem_limit: 1024M
    mem_reservation: 512M
    stop_grace_period: 5s
    sysctls:
      - net.ipv4.ip_local_port_range=1024 65000
      - net.ipv4.conf.all.accept_redirects=0
      - net.ipv4.conf.all.secure_redirects=0
      - net.ipv4.conf.all.send_redirects=0

  mysql:
    hostname: mysql
    container_name: database
    image: mysql:latest
    init: true
    restart: unless-stopped
    ports:
      - "3306:3306"
    volumes:
      - "./mysql:/var/lib/mysql:rw"
      - "/etc/timezone:/etc/timezone:ro"
      - "/etc/localtime:/etc/localtime:ro"
      #- "./initdb.sql:/docker-entrypoint-initdb.d/initdb.sql:ro"
    environment:
      - MYSQL_USER=$MYSQL_USER
      - MYSQL_DATABASE=$DATABASE
      - DB_SERVER_HOST=mysql-server
      - DB_SERVER_SOCKET=/var/run/mysqld/mysqld.sock
      - MYSQL_ROOT_HOSTS=%
      - MYSQL_CHARSET=utf8mb4
      - MYSQL_ROOT_PASSWORD=Zabbix@2024
      - MYSQL_COLLATION=utf8mb4_general_ci
      - MYSQL_ALLOW_EMPTY_PASSWORD=true
    tmpfs: /tmp
    ulimits:
      nproc: 65535
      nofile:
        soft: 20000
        hard: 40000
    deploy:
      replicas: 1
    cpus: 0.5
    mem_limit: 1024M
    mem_reservation: 512M

    stop_grace_period: 1m


  nginx:
    image: zabbix/zabbix-web-nginx-mysql:ubuntu-6.4-latest
    container_name: frontend
    hostname: nginx
    restart: always
    depends_on:
      - mysql
    ports:
      - "8080:8080"
      - "443:443"
    environment:
      - MYSQL_USER=zabbix
      - PHP_TZ="Europe/London"
      - DB_SERVER_HOST=mysql-server
      - MYSQL_DATABASE=zabbix
      - MYSQL_PASSWORD=Zabbix@2024
      - ZBX_SERVER_HOST=zabbix-server
      - PHP_FPM_PM_MAX_CHILDREN=50
      - PHP_FPM_PM_START_SERVERS=5
      - PHP_FPM_PM_MIN_SPARE_SERVERS=5
      - PHP_FPM_PM_MAX_SPARE_SERVERS=35
      - PHP_FPM_PM_MAX_REQUESTS=0
    tmpfs: /tmp
    ulimits:
      nproc: 65535
      nofile:
        soft: 20000
        hard: 40000
    deploy:
      replicas: 1
    cpus: 0.5
    mem_limit: 1024M
    mem_reservation: 512M
    links:
      - mysql
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8080/"]
      interval: 10s
      timeout: 5s
      retries: 3
      start_period: 30s
    stop_grace_period: 10s
    sysctls:
      - net.core.somaxconn=65535


### Variables ###

# $FRONTEND_IMAGE
# $FRONTEND_HOSTNAME
# $FRONTEND_CONTAINER_NAME
#
# $BACKEND_IMAGE
# $BACKEND_HOSTNAME
# $BACKEND_CONTAINER_NAME
#
#
# PHP_TZ="$ZONE"
# MYSQL_PASSWORD=$MYSQL_PASSWORD
# WEB_HOSTNAME=$WEB_HOSTNAME
# BACKEND_SERVER_HOST=$BACKEND_SERVER
#
#
#
# $FRONT_HTTP_PORT
# $FRONT_HTTPS_PORT
# MYSQL_DATABASE= $DATABASE
#
# DB_SERVER_HOST=$MYSQL_HOST
#############################################
# ===========================================



#zabbix-agent:
#container_name: zabbix-agent
#image: zabbix/zabbix-agent2:ubuntu-6.4.11
#user: root
#networks:
#- network-zabbix
#links:
#zabbix-server
#restart: always
#privileged: true
#volumes:
#- /var/run:/var/run
#ports:
#- '10050:10050'
#environment:
#-ZBX_HOSTNAME=Zabbix server
#- ZBX_SERVER_HOST=172.18.0.1

#command:
#--init-command="SET @@SESSION.SQL_LOG_BIN=0;"
#--init-command="SET @@SESSION.SQL_LOG_BIN=0;"
#--character-set-server=utf8mb4.
#--collation-server=utf8mb4_bin
#-MYSQL_USER=zabbix
#-MYSQL_ROOT_PASSWORD=carryontech
#-MYSQL_PASSWORD=carryontech
#command: --default-authentication-plugin=mysql_native_password
#command: --skip-grant-tables
#command: --skip-networking
#command: --ignore-db-dir=lost+found
#command: --initialize-insecure
#command: --disable-partition-engine-check
